name: Release CLI

on:
  release:
    types: [ created ]

permissions:
  contents: write
  packages: write

jobs:
  release-binaries:
    name: Release Executable Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [ linux ]
        goarch: [ 386, amd64, arm, arm64 ]
    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1.41
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: "go.mod"
          project_path: "./cmd/medad"
          binary_name: medad
          extra_files: LICENSE
